### ISSUE TITLE
efficientnet with FPN can not be run

### ISSUE THREAD

**Issue by jinfagang** [sxhxliang/detectron2_backbone#13]
efficient output shape are:

```
```

**Comment by jinfagang** [comment]
```
detectron2/detectron2/modeling/backbone/fpn.py", line 142, in forward
    prev_features = lateral_features + top_down_features
RuntimeError: The size of tensor a (50) must match the size of tensor b (100) at non-singleton dimension 3

```

with config:

```yaml


  BACKBONE:
    NAME: "build_efficientnet_fpn_backbone"
  EFFICIENTNET:
    NAME: "efficientnet_b1"
    # OUT_FEATURES: ["stride8", "stride16", "stride32"] # fpn produce 4 levels, only using 3 for now
    OUT_FEATURES: ["stride4", "stride8", "stride16", "stride32"]
  FPN:
    # IN_FEATURES: ["stride8", "stride16", "stride32"]
    IN_FEATURES: ["stride4", "stride8", "stride16", "stride32"]
    OUT_CHANNELS: 64
    REPEAT: 3
```
